---
title: "Preguntas y respuestas"
---
<h1>Sesión 1</h1>
<h2 style="text-align: justify;">A parte de la segmentación, ¿Qué otro propósito puede tener el aprendizaje Supervisado o es solamente para la clasificación?</h2>
<h5 style="text-align: justify;"><span style="color: #808080;"> Inicialmente, el aprendizaje supervisado tiene como propósito predecir el valor correspondiente a cualquier objeto de entrada después de haber visto una serie de eventos en los datos de entrenamiento. Pero no está limitado únicamente a la segmentación, también se puede inferir relaciones de asociación entre los atributos y relaciones de agrupamiento con propósitos diversos. Por ejemplo: considere un modelo basado en los datos históricos de pagos y valores de cuota, además de datos demográficos y socioeconómicos, su categoría final es el riesgo de morosidad. De esta información se pueden generar otras reglas de asociación para la detección de anomalías entre los atributos y la variable objetivo, para identificar datos que no son considerados habituales.</span></h5>
<p>&nbsp;</p>
<h2 style="text-align: justify;">Preguntas relacionadas con R: La función Apply y su estructura.</h2>
<h5 style="text-align: justify;"><span style="color: #808080;"> Esta función es usada para aplicar una función a cada elemento de una estructura de datos. Normalmente se usan para tener resumenes de listas, dataframes, matrices.</span></h5>
<h5><span style="color: #808080;">Apply tiene la siguiente estructura (Dataframe , el marge: 1 filas y 2: columnas , Función)</span></h5>
<h5><span style="color: #808080;">Ejemplos: </span></h5>
<h5><span style="color: #808080;">apply (data, 2, mean)</span></h5>
<h5><span style="color: #808080;">apply (data, 2, median)</span></h5>
<h5><span style="color: #808080;">apply (data, 2, summary)</span></h5>
<p>&nbsp;</p>
<h2 style="text-align: justify;"> ¿Qué tipo de error se usó para validar el modelo?</h2>
<h5 style="text-align: justify;"><span style="color: #808080;"> Los errores son absolutos, los errores relativos se miden en porcentajes. Para tener un error relativo se debe dividir por el valor real. Son valores absolutos porque se escoge el valor real y el valor predicho.</span></h5>
<p>&nbsp;</p>
<h2 style="text-align: justify;"> ¿Qué hace que una clasificación binaria sea del tipo {0,1} o del tipo {-1,1} o es sólo preferencia de elección?</h2>
<h5 style="text-align: justify;"><span style="color: #808080;"> No se ha generado la respuesta en el momento.</span></h5>
<p>&nbsp;</p>
<h2 style="text-align: justify;"> ¿Se pueden sumar esas dos matrices si son simétricas?</h2>
<h5 style="text-align: justify;"><span style="color: #808080;"> No se ha generado la respuesta en el momento.</span></h5>
<p>&nbsp;</p>
<h2 style="text-align: justify;"> Preguntas relacionadas con R: ¿Hay técnicas para seleccionar la cantidad de datos de validación y de entrenamiento?</h2>
<h5 style="text-align: justify;"><span style="color: #808080;"> No se ha generado la respuesta en el momento.</span></h5>
<p>&nbsp;</p>
<h2 style="text-align: justify;"> Preguntas relacionadas con R: ¿Por qué una función dentro de otra es mala práctica?</h2>
<h5 style="text-align: justify;"><span style="color: #808080;"> No se ha generado la respuesta en el momento.</span></h5>


<p>&nbsp;</p>